zuihou:
  log:
    enabled: false

spring:
  cloud:
    gateway:
      x-forwarded:
        prefixEnabled: false
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: file
          uri: lb://zuihou-file-server
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: authority
          uri: lb://zuihou-authority-server
          predicates:
            - Path=/authority/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: msgs
          uri: lb://zuihou-msgs-server
          predicates:
            - Path=/msgs/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: demo
          uri: lb://zuihou-demo-server
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: order
          uri: lb://zuihou-order-server
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'

filters:
  - name: Hystrix
    args:
      name: default
      fallbackUri: 'forward:/fallback'


server:
  port: 8760
  servlet:
    context-path: /api  # = server.servlet.context-path

authentication:
  user:
    header-name: token
    pub-key: client/pub.key    # 解密
